### ISSUE TITLE
Notes on using singularity in projects WGC2020 and Endorse

### ISSUE THREAD

**Issue by Paulie14** [flow123d/docker-config#15]
- [x] python in both `docker://flow123d/flow123d-dev-gnu-rel:3.1.0` and `docker://flow123d/geomop-base-gnu:3.1.0` lack the package for virtual environment (`python3.8-venv`)

**Comment by jbrezmorf** [comment]
serious issue

@martinspetlik please add it to base-* Dockerfiles. 
Point is that Singularity does not support containers so venv can be used to install further python packages to the mounted user directory.
